<?php
/** @var Expertime\Import\Block\Adminhtml\Import\Customer $this */

$customers = $this->getCustomers();
?>

<?php if(count($customers) > 0): ?>
    <div class="customers row">
        <div class="col-12">
            <p class="title"><?= __('Customers:') ?></p>
            <div class="row">
                <div class="col-6">
                <?php foreach ($customers as $key => $value) : ?>
                    <pre><?php print_r($value); ?></pre>
                <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
